apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-install
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-install
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: manager-install
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: manager-install
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 1800
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: manager-install
      automountServiceAccountToken: true
      enableServiceLinks: false
      containers:
      - name: kubectl
        image: dtzar/helm-kubectl
        command: ["/bin/bash", "-euxo", "pipefail", "-c"]
        args:
          - |-
            kubectl apply -f 'https://github.com/cni-benchmark/test-cases/raw/refs/heads/main/kubernetes/manager/flux-system/gotk-components.yaml'
            kubectl apply -k 'https://github.com/cni-benchmark/test-cases.git/kubernetes/manager/flux-system?ref=main'
            kubectl apply -k 'https://github.com/cni-benchmark/test-cases.git/kubernetes/manager?ref=main'
            exit 0
        resources:
          limits:
            cpu: "1.0"
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: tmp
            mountPath: /tmp
            readOnly: false
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 10Mi
