apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: grafana
spec:
  chart: grafana
  version: "<10.0.0"
  sourceRef:
    kind: HelmRepository
    name: grafana
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chartRef:
    kind: HelmChart
    name: grafana
  values:
    nameOverride: grafana
    fullnameOverride: grafana
    service:
      type: NodePort
      nodePort: 30001
    adminUser: admin
    adminPassword: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: InfluxDB
            type: influxdb
            access: proxy
            url: http://influxdb
            jsonData:
              version: Flux
              organization: primary
              defaultBucket: primary
            secureJsonData:
              token: replaced
