# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
  - storageclass.yaml
labels:
  - pairs:
      app.kubernetes.io/name: local-path-provisioner
      app.kubernetes.io/component: local-path-provisioner
    includeSelectors: true
    includeTemplates: true
configMapGenerator:
  - name: local-path-config
    files:
      - config.json
      - setup=setup.sh
      - teardown=teardown.sh
      - helperPod.yaml
    options:
      disableNameSuffixHash: true
images:
  - name: local-path-provisioner
    newName: docker.io/rancher/local-path-provisioner
    newTag: v0.0.31
    digest: sha256:80496fdeb307541007621959aa13aed41d31db9cd2dc4167c19833e0bfa3878c
