apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: influxdb
spec:
  url: oci://registry-1.docker.io/bitnamicharts/influxdb
  ref:
    semver: '<7.0.0'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
spec:
  releaseName: influxdb
  chartRef:
    kind: OCIRepository
    name: influxdb
  values:
    nameOverride: influxdb
    fullnameOverride: influxdb
    auth:
      enabled: true
      admin:
        username: admin
        password: password
        token: token
        org: primary
        bucket: primary
    influxdb:
      resourcesPreset: none
      updateStrategy:
        type: Recreate
      pdb:
        create: false
      service:
        type: NodePort
        ports:
          http: 80
        nodePorts:
          http: 30002
      startupProbe:
        enabled: false
      readinessProbe:
        enabled: false
