apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cert-manager
spec:
  chart: cert-manager
  version: "<2.0.0"
  sourceRef:
    kind: HelmRepository
    name: jetstack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chartRef:
    kind: HelmChart
    name: cert-manager
  values:
    installCRDs: true
    nameOverride: cert-manager
    fullnameOverride: cert-manager
    enableCertificateOwnerRef: true
    prometheus:
      enabled: false
