apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: grafana
spec:
  chart: grafana
  version: "<10.0.0"
  sourceRef:
    kind: HelmRepository
    name: grafana
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chartRef:
    kind: HelmChart
    name: grafana
  values:
    nameOverride: grafana
    fullnameOverride: grafana
    deploymentStrategy:
      type: Recreate
    dnsPolicy: ClusterFirstWithHostNet
    service:
      enabled: false
      targetPort: 80 # Sets port in the container
    env:
      GF_SERVER_HTTP_PORT: "80"
    adminUser: admin
    adminPassword: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: PostgreSQL
            type: postgres
            url: postgresql:5432
            user: username
            secureJsonData:
              password: password
            jsonData:
              database: database
              sslmode: disable
              maxOpenConns: 200
              maxIdleConns: 100
              maxIdleConnsAuto: true
              connMaxLifetime: 14400
              postgresVersion: 1700 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
              timescaledb: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |-
              - op: replace
                path: /spec/template/spec/hostNetwork
                value: true
              - op: add
                path: /spec/template/spec/containers/0/securityContext/capabilities/add
                value: ["NET_BIND_SERVICE"]
              - op: remove
                path: /spec/template/spec/containers/0/readinessProbe
              - op: remove
                path: /spec/template/spec/containers/0/livenessProbe
