apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manager
  namespace: default
spec:
  path: &path "${KS_PATH}/manager"
  postBuild:
    substitute:
      KS_PATH: *path
      NAMESPACE: default
