apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${NAMESPACE}
resources:
  - postgresql.yaml
  - grafana.yaml
components:
  - ../../lib/flux-common
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboard.json
    options:
      disableNameSuffixHash: true
