apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgresql
spec:
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: '<17.0.0'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  releaseName: postgresql
  chartRef:
    kind: OCIRepository
    name: postgresql
  values:
    nameOverride: postgresql
    fullnameOverride: postgresql
    auth:
      postgresPassword: postgres
      username: username
      password: password
      database: database
    primary:
      resourcesPreset: none
      pdb:
        create: false
      hostNetwork: true
      persistence:
        enabled: true
        size: 1Gi
      networkPolicy:
        enabled: false
      extendedConfiguration: |-
        # DB Version: 17
        # OS Type: linux
        # DB Type: web
        # Total Memory (RAM): 1 GB
        # CPUs num: 2
        # Connections num: 5000
        # Data Storage: ssd

        max_connections = 5000
        shared_buffers = 256MB
        effective_cache_size = 768MB
        maintenance_work_mem = 64MB
        checkpoint_completion_target = 0.9
        wal_buffers = 7864kB
        default_statistics_target = 100
        random_page_cost = 1.1
        effective_io_concurrency = 32
        work_mem = 64kB
        huge_pages = off
        min_wal_size = 128MB
        max_wal_size = 512MB
