apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: cluster-api-
resources:
  - operator.yaml
  - ks-core-provider.yaml
replacements:
  - source:
      kind: HelmRepository
    targets:
      - select:
          kind: HelmChart
        fieldPaths:
          - .spec.sourceRef.name
  - source:
      kind: HelmChart
    targets:
      - select:
          kind: HelmRelease
        fieldPaths:
          - .spec.chartRef.name
  - source:
      kind: HelmRelease
    targets:
      - select:
          kind: HelmRelease
        fieldPaths:
          - .spec.releaseName
          - .spec.values.nameOverride
          - .spec.values.fullnameOverride
