apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: &path ./kubernetes/flux-system
  postBuild:
    substitute:
      KS_PATH: *path
