apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: system
spec:
  path: &path "${KS_PATH}/system"
  postBuild:
    substitute:
      KS_PATH: *path
      NAMESPACE: system
