apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-install
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runner-install
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: runner-install
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: runner-install
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 1800
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: runner-install
      automountServiceAccountToken: true
      enableServiceLinks: false
      containers:
      - name: kubectl
        image: dtzar/helm-kubectl
        command: ["/bin/bash", "-euxo", "pipefail", "-c"]
        args:
          - |-
            kubectl apply -f 'https://github.com/cni-benchmark/test-cases/raw/refs/heads/main/kubernetes/flux-system/gotk-components.yaml'
            kubectl apply -k 'https://github.com/cni-benchmark/test-cases.git/kubernetes/flux-system?ref=main'
            kubectl apply -k 'https://github.com/cni-benchmark/test-cases.git/kubernetes/runner?ref=main'
            exit 0
        resources:
          limits:
            cpu: "1.0"
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: tmp
            mountPath: /tmp
            readOnly: false
          - name: data
            mountPath: /data
            readOnly: true
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 10Mi
        - name: data
          configMap:
            name: runner-install
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-install
  namespace: kube-system
data:
  ks.yaml: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: test-cases
      namespace: default
    spec:
      sourceRef:
        kind: GitRepository
        name: test-cases
        namespace: flux-system
      path: ./kubernetes/tests
      force: true
      interval: 1h
      prune: true
      timeout: 2m
      wait: false
      patches:
        - target:
            kind: Job
            labelSelector: mode=client
          patch: |-
            - op: add
              path: /spec/template/spec/containers/0/env/-
              value:
                name: DATABASE_URL
                value: postgresql://username:password@postgresql.default:5432/database
            - op: add
              path: /spec/template/spec/containers/0/env/-
              value:
                name: DURATION
                value: "10"
