apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runner
  namespace: flux-system
spec:
  path: &path ./kubernetes/runner
  postBuild:
    substitute:
      KS_PATH: *path
