apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../lib/cni-install
configMapGenerator:
  - name: cni-install
    files:
      - entrypoint.sh
      - values.yaml
  - name: cni-info
    envs:
      - cni-info.env
    options:
      disableNameSuffixHash: true
