apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${NAMESPACE}
resources:
  - aws.yaml
secretGenerator:
  - name: aws-configuration
    literals:
      - AWS_B64ENCODED_CREDENTIALS=# empty
    options:
      disableNameSuffixHash: true
