version: "3"

set: [pipefail]

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run Go tests
    cmds:
      - go test ./... -v -ginkgo.v

includes:
  kind:
    taskfile: ./kind/taskfile.yaml
    dir: ./kind
